### ISSUE TITLE
The code for load_data should be provided in the notebook

### ISSUE THREAD

**Issue by AngCamp** [RoyVII/cnn-ripple#3]
Respectfully I do not feel the notebook provided to demo how to use the model does a very good job of it. https://colab.research.google.com/github/RoyVII/cnn-ripple/blob/main/src/notebooks/cnn-example.ipynb#scrollTo=ef0688bc  It's not clear how the data should be formatted to be provided as input to the model, I'm guessing its takes  an array of shape [time, 8,8].  Simply running X.shape would have cleared up this confusion.  I know you describe this in the methods section of the paper but its a bit difficult to keep track of it all.  Also the code for making the sliding window should have been provided.  I understand that making a sliding window may be a trivial challenge for someone in CS but I am a biologist, so it's not that easy for me.  I found a solution that works I think https://stackoverflow.com/questions/6811183/rolling-window-for-1d-arrays-in-numpy/6811241#6811241

Also note numpy has a function which can do this is available as of numpy version 1.20.0 https://numpy.org/devdocs/reference/generated/numpy.lib.stride_tricks.sliding_window_view.html  you can accomplish this with
 ```
import numpy
from numpy.lib.stride_tricks import sliding_window_view
windowsize=16
stepsize=8
sliding_window_view(X[:,0], windowsize)[::stepsize]
```

But your environment is frozen at numpy 1.8.5 and the python version prevents this from being updated.  IMO you should probably either update the version of this so that the simplest, most widely available and therefor reproducible code can be used or provide the code you used.

**Comment by RoyVII** [comment]
Hi,

Sorry if the in-code explanation was not clear. As explained in the notebook, the input data must be a two-dimensional array with shape **[Number of samples, Number of channels]**, with samples being recorded at the sampling frequency specified in argument _fs_ and number of channels always being _8_. 

For example, you can see that the example data provided has a shape of **(22326272, 8)** with 22326272 samples recorded at 30kHz(744.21 seconds of recording) in 8 different channels, as shown by the print in that cell.

All the code used in this notebook, including how to generate the sliding windows, is publicly available in this same repository (https://github.com/PridaLab/cnn-ripple/tree/main/src/cnn).

**Comment by AngCamp** [comment]
Thank you for pointing me to the code I appreciate it.  Sorry I skipped using sys which is probably where my problems started.
